Add Organizational Data link to myteam-explore.md
MicrosoftDocs/Viva pull request #285
Opened 2022-03-12 11:59 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/issues/273.

2022-03-14 11:34 UTC, JohanFreelancer9 commented on Viva/insights/Use/myteam-explore.md
> +The **Group insights** section is available to managers who the Viva Insights admin specifies. Group insights are based all employees that report up to you as the manager, not just your immediate gro
```suggestion
The **Group insights** section is available to managers whom the Viva Insights admin specifies. Group insights are based on all employees that report up to you as the manager, not just your immediate group members or direct reports. The admin uses the organizational data that is uploaded into Viva Insights in Workplace Analytics or that’s presented in Azure AD. For more information, see [Organizational data](organizational-data.md).
```

2022-03-14 11:34 UTC, JohanFreelancer9 requested changes
Copy review - not related, but additional changes, please.

2022-03-14 11:42 UTC, JohanFreelancer9 approved these changes

2022-03-18 04:22 UTC, scanum commented
@madehmer PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-12-01 12:19 UTC, dariomws commented
@madehmer PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-12-01 12:19 UTC, dariomws commented
@madehmer PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-04-10 06:30 UTC, dariomws commented
@madehmer PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-05-12 18:34 UTC, tiburd commented
Closing because this article has been deleted. 
Redirect points to: 
https://github.com/MicrosoftDocs/Viva/blob/public/Viva/insights/org-team-insights/team-insights.md.

2023-05-12 18:34 UTC, closed without merging