Update required role in viva-insights-my-org.md
MicrosoftDocs/Viva pull request #286
Opened 2022-03-12 14:03 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/issues/272.

Reference:
https://docs.microsoft.com/viva/insights/use/user-roles

2022-03-14 11:37 UTC, JohanFreelancer9 commented on Viva/insights/Use/viva-insights-my-org.md
>  Ask your admin also needs to install and set up the Viva Insights app in Teams for the organization. See [Admin tasks](../personal/teams/viva-teams-app-admin-tasks.md) for details.
```suggestion
Your admin also needs to install and set up the Viva Insights app in Teams for the organization. See [Admin tasks](../personal/teams/viva-teams-app-admin-tasks.md) for details.
```

2022-03-14 11:37 UTC, JohanFreelancer9 requested changes
Copy review - Not related but one additional change, please.

2022-03-14 11:42 UTC, JohanFreelancer9 approved these changes

2022-03-18 04:22 UTC, scanum commented
@madehmer PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-11-22 19:37 UTC, closed without merging