Update configure-sharepoint-content-source.md
MicrosoftDocs/Viva pull request #332
Opened 2022-06-09 15:23 UTC by soyalejolopez

Include note regarding supportability for using SPO custom vanity URLs.

2022-06-12 07:22 UTC, JohanFreelancer9 commented on Viva/learning/configure-sharepoint-content-source.md
> +  > SharePoint Online Custom (Vanity) URLs that do not conform to "tenantName.sharepoint.com" are currently not supported. Please open a support case if you're in this scenario and need help.
```suggestion
  > SharePoint Online Custom (Vanity) URLs that do not conform to "tenantName.sharepoint.com" are currently not supported. Kindly open a support case if you're in this scenario and need help.   
```

2022-06-12 07:28 UTC, JohanFreelancer9 requested changes
Copy review - @soyalejolopez, kindly commit the suggested change (for info, we do not use the word "please" in Microsoft docs, except in some very specific cases, which do not apply here). Many thanks.

2022-06-13 14:06 UTC, soyalejolopez commented
Looks good, thank you Johan.

2022-06-13 15:38 UTC, JohanFreelancer9 approved these changes

2023-10-02 05:09 UTC, scanum commented
@daisyfell 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-02 16:14 UTC, daisyfell commented
Reassigning to @bhaswatic who is the current writer/cpm of the Viva Learning set

2025-04-16 15:05 UTC, closed without merging