Add instructions for pinning the Viva Connections app
MicrosoftDocs/Viva pull request #335
Opened 2022-06-21 17:57 UTC by sympmarc

I discussed this with @pamgreen-msft on a call today. I'd guess the majority of people setting up Viva Connections want to pin the app to the top of the Teams App Bar. That's how they have seen it shown in all of the demos and screenshots from Microsoft. When I was setting up Viva Connections for a client today, I sort of knew I needed to pin the app, but I slid right past the buttle about it in this article.

So, my suggested edit is to include the "fastest path to joy" to accomplish this, with a link to info about Setup Policies rather than just linking to that article, which covers many other aspects of the topic.

2022-06-23 04:08 UTC, JohanFreelancer9 commented on Viva/connections/add-viva-connections-app.md
> +Most organizations want to pin the Viva Connections app to the top of the Teams App Bar for all users. This can be accomplished by changing the pinned apps in the Teams Admin Center under [Setup poli
```suggestion
Most organizations want to pin the Viva Connections app to the top of the Teams app bar for all users. This can be accomplished by changing the pinned apps in the Microsoft Teams admin center under [Setup policies](/MicrosoftTeams/teams-app-setup-policies).
```

2022-06-23 04:11 UTC, JohanFreelancer9 commented on Viva/connections/add-viva-connections-app.md
> +7. Use the two horizontal lines next to the app to drag it to the top of the app list
```suggestion
1. Navigate to the **Teams admin center** > **Teams apps** > **Setup policies**.
2. Select **Global (Org-wide default)** (this is the default policy for all users).
3. Scroll down to **Pinned apps**.
4. Select **+ Add apps**.
5. In the second box, search for the Viva Connections app you enabled with the name you gave it, for example, Intranet.
6. Select **Add** next to the app name and then **Add** at the bottom of the panel.
7. Use the two horizontal lines next to the app to drag it to the top of the app list.
```

2022-06-23 04:12 UTC, JohanFreelancer9 commented on Viva/connections/add-viva-connections-app.md
> +8. Click **Save** at the bottom of the page
```suggestion
8. Select **Save** at the bottom of the page.
```

2022-06-23 04:14 UTC, JohanFreelancer9 commented on Viva/connections/add-viva-connections-app.md
> +If your needs are different, [learn more about Teams app set up policies](/MicrosoftTeams/teams-app-setup-policies).
```suggestion
If your needs are different, [learn more about Teams app setup policies](/MicrosoftTeams/teams-app-setup-policies).
```

2022-06-23 04:16 UTC, JohanFreelancer9 requested changes
Copy review - @sympmarc, kindly commit the suggested changes. Many thanks.

2022-07-05 19:07 UTC, sympmarc commented
@scanum Sorry - but until you closed this, I missed the notifications for the proposed changes. Could we please re-open this PR so we can merge the changes?

@JohanFreelancer9 - I agree with your changes, since they bring my suggested text in line with the docs standards. Thanks!

2022-07-12 23:04 UTC, scanum commented
@Holland-ODSP PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-07-12 23:34 UTC, Holland-ODSP approved these changes

2022-07-12 23:34 UTC, merged