Fix links in create-sharepoint-home-site-for-viva-connections.md
MicrosoftDocs/Viva pull request #379
Opened 2022-08-09 07:09 UTC by dariomws

Closes https://github.com/MicrosoftDocs/Viva/issues/348.

2022-08-10 05:37 UTC, JohanFreelancer9 commented on Viva/connections/create-sharepoint-home-site-for-viva-connections.md
> +Start with a [modern SharePoint communication site](https://support.microsoft.com/office/create-a-communication-site-in-sharepoint-7fb44b20-a72f-4d2c-9173-fc8f59ba50eb). Next, [start adding sections]
```suggestion
Start with a [modern SharePoint communication site](https://support.microsoft.com/office/create-a-communication-site-in-sharepoint-7fb44b20-a72f-4d2c-9173-fc8f59ba50eb). Next, [start adding sections](https://support.microsoft.com/office/add-sections-and-columns-on-a-sharepoint-modern-page-fc491eb4-f733-4825-8fe2-e1ed80bd0899) following the diagram in the site sections summary. Then, add and edit web parts. The guidance for customizing web parts can be applied when you are in edit mode for each web part. 
```

2022-08-10 05:38 UTC, JohanFreelancer9 commented on Viva/connections/create-sharepoint-home-site-for-viva-connections.md
> +After the site is built, edit site details to create a customized design that aligns with your organizations brand and identity. These [site details can be managed](https://support.microsoft.com/offi
```suggestion
After the site is built, edit site details to create a customized design that aligns with your organization's brand and identity. These [site details can be managed](https://support.microsoft.com/office/customize-your-sharepoint-site-320b43e5-b047-4fda-8381-f61e8ac7f59b) from **Settings** > **Change the look**.
```

2022-08-10 05:39 UTC, JohanFreelancer9 requested changes
Copy review - two minor additional edits, please.

2022-08-10 10:53 UTC, JohanFreelancer9 approved these changes

2022-08-15 19:10 UTC, scanum commented
@Holland-ODSP PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-08-18 13:10 UTC, Holland-ODSP approved these changes

2022-08-18 13:10 UTC, merged