Update sharepoint-permissions.md
MicrosoftDocs/Viva pull request #382
Opened 2022-08-12 14:09 UTC by MarcoCarampanta

I think the section I changed should be notably separate/highlighted & well identified as to prevent any mixup.

If we just leave the text "to remove (...) content, please follow:" in the exact same style/font with no separators i feel it will induce users in error (and already led some people in error who were mixed up "why are they now removing access")

I would kindly ask your insight from the Writers Team though for the best form to phrase it :) ... I was undecided between leaving the same term, or just switching to "Remove Content Access" ... but felt somewhat "empty" ... I will leave that to your decision! :)

Thank you so much for the support & help!

2022-08-13 08:20 UTC, JohanFreelancer9 commented on Viva/learning/sharepoint-permissions.md
> +## To remove unintentionally surfaced content
```suggestion
## Remove unintentionally surfaced content
```

2022-08-13 08:21 UTC, JohanFreelancer9 requested changes
Copy review - @MarcoCarampanta, kindly commit the minor suggested change. Many thanks.

2022-08-23 06:02 UTC, scanum commented
@daisyfell PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-08-23 14:11 UTC, daisyfell commented
assigning to @bhaswatic

2022-08-23 21:25 UTC, bhaswatic commented
Hi all. The changes have been made in the private repo and will be live soon. 
Thank you, 
Bhas

2022-08-23 21:25 UTC, closed without merging