Update topic-experiences-discovery-curation.md
MicrosoftDocs/Viva pull request #395
Opened 2022-08-30 21:28 UTC by keremyuceturk

Updating with some of our newer experiences in Teams and Outlook on the web.

2022-08-31 08:25 UTC, JohanFreelancer9 commented on Viva/topics/topic-experiences-discovery-curation.md
> +Viva Topics then, when the context is appropriate, will suggest these topics to be highlighted or displayed on different Microsoft 365 apps, such as SharePoint modern  pages or on Outlook on the web.
```suggestion
Viva Topics then, when the context is appropriate, will suggest these topics to be highlighted or displayed on different Microsoft 365 apps, such as SharePoint modern pages or on Outlook on the web. The topic can also be directly referenced on SharePoint pages by an author, on Microsoft Teams in chat messages, as well as in Outlook on the web while writing emails. When a user is curious to learn more about a topic, they can select a topic to view a **Topic summary** card that provides a short description. And if they want to learn more, they can select a **Topic details** link in the summary to open the detailed topic page.
```

2022-08-31 08:26 UTC, JohanFreelancer9 requested changes
Copy review - @keremyuceturk, kindly commit the minor suggested change to remove the extra space. Many thanks.

2022-09-08 05:55 UTC, JohanFreelancer9 approved these changes

2023-10-02 05:10 UTC, scanum commented
@ruthholls 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-02 18:31 UTC, daisyfell commented
Thanks @keremyuceturk , in the future if you want you can use the private repo to submit your changes so they go through with higher priority https://review.learn.microsoft.com/en-us/office-authoring-guide/getting-started-read-write?branch=main

2023-10-02 18:31 UTC, merged