Update edit-viva-home.md to retrieve the current state of home site experience before updating
MicrosoftDocs/Viva pull request #505
Opened 2023-01-21 11:30 UTC by cts-mbiswas

IT admins are asking for a way to retrieve the current state of the default landing to the home site before making a change. IT admins always do not have Viva Connections enabled as some orgs have IT managed by partners . Proposing a change to retrieve the current state of default landing to the home site before making a change.

2023-01-23 05:40 UTC, JohanFreelancer9 commented on Viva/connections/edit-viva-home.md
> +3.	Run `Get-SPOHomesite|fl and look for the value of VivaConnectionsDefaultStart <$true/$false>` for the current landing expereince.
```suggestion
3.	Run `Get-SPOHomesite|fl and look for the value of VivaConnectionsDefaultStart <$true/$false>` for the current landing experience.
```

2023-01-23 05:45 UTC, JohanFreelancer9 commented on Viva/connections/edit-viva-home.md
> +$Site = Get-SPOHomeSite
```suggestion
`$Site = Get-SPOHomeSite`
```

2023-01-23 05:46 UTC, JohanFreelancer9 commented on Viva/connections/edit-viva-home.md
> +$Site.VivaConnectionsDefaultStart
```suggestion
`$Site.VivaConnectionsDefaultStart`
```

2023-01-23 05:48 UTC, JohanFreelancer9 commented on Viva/connections/edit-viva-home.md
> +**To set the default landing to the home site:**
```suggestion
**To set the default landing to the home site:**

```

2023-01-23 05:54 UTC, JohanFreelancer9 requested changes
Copy review - @cts-mbiswas, kindly commit the suggested changes. Many thanks.

2023-10-02 05:13 UTC, scanum commented
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

2023-10-02 05:13 UTC, closed without merging

2023-10-03 21:32 UTC, cts-mbiswas commented
Hello Team

I was wanting to follow up on this as I was not able to see the suggested changes, but now I see the feedback item closed with seems an action step pending one me. Can you please guide me on the next steps please  so that we can get the recommended changes published.

Regards,
Manas

From: Manuela Scanu ***@***.***>
Sent: Monday, October 2, 2023 6:14 AM
To: MicrosoftDocs/Viva ***@***.***>
Cc: Manas Kumar Biswas ***@***.***>; Assign ***@***.***>
Subject: Re: [MicrosoftDocs/Viva] Update edit-viva-home.md to retrieve the current state of home site experience before updating (PR #505)


Closed #505<https://github.com/MicrosoftDocs/Viva/pull/505>.

-
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftDocs/Viva/pull/505#event-10522004280>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ADZXBJUY2ONSDD62LOAHWYDX5JEP7ANCNFSM6AAAAAAUCLFHPE>.
You are receiving this because you were assigned.Message ID: ***@***.******@***.***>>

2023-10-04 07:41 UTC, JohanFreelancer9 commented
@scanum

2023-10-05 11:21 UTC, cts-mbiswas commented
Thanks JohanFreelancer9 - including my original message as well.


From: Manas Kumar Biswas
Sent: Wednesday, October 4, 2023 3:03 AM
To: 'MicrosoftDocs/Viva' ***@***.******@***.***>; MicrosoftDocs/Viva ***@***.******@***.***>
Cc: Assign ***@***.******@***.***>; Manas Kumar Biswas ***@***.******@***.***>
Subject: RE: [MicrosoftDocs/Viva] Update edit-viva-home.md to retrieve the current state of home site experience before updating (PR #505)

Hello Team

I was wanting to follow up on this as I was not able to see the suggested changes, but now I see the feedback item closed with seems an action step pending one me. Can you please guide me on the next steps please  so that we can get the recommended changes published.

Regards,
Manas


From: JohanFreelancer9 ***@***.***>
Sent: Wednesday, October 4, 2023 1:11 PM
To: MicrosoftDocs/Viva ***@***.***>
Cc: Manas Kumar Biswas ***@***.***>; Assign ***@***.***>
Subject: Re: [MicrosoftDocs/Viva] Update edit-viva-home.md to retrieve the current state of home site experience before updating (PR #505)


@scanum<https://github.com/scanum>

-
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftDocs/Viva/pull/505#issuecomment-1746313439>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ADZXBJVA7FE2NS7HF5ECU7TX5UHKLAVCNFSM6AAAAAAUCLFHPGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONBWGMYTGNBTHE>.
You are receiving this because you were assigned.Message ID: ***@***.******@***.***>>

2023-10-16 08:34 UTC, cts-mbiswas commented
Hello Team,

Any pointers regarding my request below..

Regards,
Manas

From: Manas Kumar Biswas ***@***.***>
Sent: Wednesday, October 4, 2023 3:03 AM
To: MicrosoftDocs/Viva ***@***.***>; MicrosoftDocs/Viva ***@***.***>
Cc: Assign ***@***.***>; Manas Kumar Biswas ***@***.***>
Subject: RE: [MicrosoftDocs/Viva] Update edit-viva-home.md to retrieve the current state of home site experience before updating (PR #505)

Hello Team

I was wanting to follow up on this as I was not able to see the suggested changes, but now I see the feedback item closed with seems an action step pending one me. Can you please guide me on the next steps please  so that we can get the recommended changes published.

Regards,
Manas

From: Manuela Scanu ***@***.******@***.***>>
Sent: Monday, October 2, 2023 6:14 AM
To: MicrosoftDocs/Viva ***@***.******@***.***>>
Cc: Manas Kumar Biswas ***@***.******@***.***>>; Assign ***@***.******@***.***>>
Subject: Re: [MicrosoftDocs/Viva] Update edit-viva-home.md to retrieve the current state of home site experience before updating (PR #505)


Closed #505<https://github.com/MicrosoftDocs/Viva/pull/505>.

-
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftDocs/Viva/pull/505#event-10522004280>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ADZXBJUY2ONSDD62LOAHWYDX5JEP7ANCNFSM6AAAAAAUCLFHPE>.
You are receiving this because you were assigned.Message ID: ***@***.******@***.***>>