Update set-up-topic-experiences.md
MicrosoftDocs/Viva pull request #541
Opened 2023-03-01 17:25 UTC by cjtancortex

Added Groups admin to required AAD roles

2023-03-02 10:28 UTC, JohanFreelancer9 requested changes
Copy review - @cjtancortex, kindly commit the minor additional change. Many thanks.

2023-03-05 09:08 UTC, JohanFreelancer9 approved these changes

2023-10-02 05:14 UTC, scanum commented
@ruthholls 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2024-02-06 21:56 UTC, lizap commented
Change made in the source and live on the page: https://learn.microsoft.com/en-us/microsoft-365/topics/set-up-topic-experiences?view=o365-worldwide

2024-02-06 21:56 UTC, closed without merging