Update use-the-link-card.md
MicrosoftDocs/Viva pull request #557
Opened 2023-03-21 22:00 UTC by lucabandMSFT

added Sway entry in the table at the bottom of the doc.

2023-03-22 13:48 UTC, JohanFreelancer9 commented on Viva/connections/use-the-link-card.md
> +| Sway  | Sway opens within Teams, user is asked to sign-in on the first time, and user doesn’t need to authenticate again if they stay signed in. | Sway opens within Teams, user is asked to sign-in
```suggestion
| Sway  | Sway opens within Teams and the user is asked to sign in the first time. The user doesn’t need to authenticate again if they stay signed in. | Sway opens within Teams and the user is asked to sign in the first time. The user doesn’t need to authenticate again if they stay signed in.            |
```

2023-03-22 13:59 UTC, JohanFreelancer9 requested changes
Copy review - @lucabandMSFT, kindly commit the suggested changes. Many thanks.

2023-03-25 04:26 UTC, lucabandMSFT reviewed
@JohanFreelancer9 , looks like I can't approve here. Is there anything I have to do?

2023-03-25 10:56 UTC, JohanFreelancer9 approved these changes

2023-03-25 10:58 UTC, JohanFreelancer9 commented
> @JohanFreelancer9 , looks like I can't approve here. Is there anything I have to do?

@lucabandMSFT, nothing more is needed from you at this time. Many thanks.

2023-10-02 05:14 UTC, scanum commented
@Holland-ODSP 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-02 14:37 UTC, Holland-ODSP approved these changes

2023-10-02 14:39 UTC, merged