Update check-in owners steps on objective-delegation.md
MicrosoftDocs/Viva pull request #558
Opened 2023-03-22 16:49 UTC by dariomws

Closes https://github.com/MicrosoftDocs/Viva/issues/536

2023-03-24 17:46 UTC, JohanFreelancer9 commented on Viva/goals/objective-delegation.md
> +2. Identify the objective/key result you want to share with another individual. Then select the new owners via the **Owner** option under **Details** section. You can assign multiple owners for the O
```suggestion
2. Identify the objective/key result you want to share with another individual, then select the new owners via the **Owner** option in the **Details** section. You can assign multiple owners for the OKR.
```

2023-03-24 17:47 UTC, JohanFreelancer9 commented on Viva/goals/objective-delegation.md
> +3. After you assign owners, use the **Check-in owner** dropdown under **Progress** section to select the user who will be responsible for making check-ins. That user will start receiving check-in rem
```suggestion
3. After you assign owners, use the **Check-in owner** dropdown in the **Progress** section to select the user who will be responsible for making check-ins. That user will start receiving check-in reminders.
```

2023-03-24 17:47 UTC, JohanFreelancer9 requested changes
Copy review.

2023-03-25 02:05 UTC, scanum commented
@dariomws

2023-03-25 11:12 UTC, JohanFreelancer9 approved these changes

2023-03-30 05:40 UTC, scanum commented
@RaSanders-MSFT 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-03-30 17:00 UTC, RaSanders-MSFT commented
Changes look good!

Do I need to add the sign off label, or press the "merge pull request" button?

2023-03-30 20:17 UTC, dariomws commented
@RaSanders-MSFT, merge pull request, please. Thanks!

2023-03-30 20:22 UTC, merged