Update org-data-overview.md
MicrosoftDocs/Viva pull request #559
Opened 2023-03-23 11:00 UTC by dariomws

Closes https://github.com/MicrosoftDocs/Viva/issues/520

2023-03-24 17:57 UTC, JohanFreelancer9 commented on Viva/insights/advanced/admin/org-data-overview.md
> +The advanced insights app can get organizational data in one of two ways: through Azure Active Directory, which is the default setting, or through an organizational data file that you as an admin upl
```suggestion
The advanced insights app can get organizational data in one of two ways: through Azure Active Directory, which is the default setting, or through an organizational data file that you as an admin upload. Azure Active Directory automatically syncs with the advanced insights app and provides data for the **PersonId**, **ManagerId**, **Organization**, **Domain**, and **Timezone** attributes. Domain will be based on the email address value of the user in Azure Active Directory and Timezone is synced from the Outlook settings. If you want to include more attributes, for example, those we discuss in [Prepare organizational data](prepare-org-data.md#attribute-reference), then you'd want to choose a data file as your source.
```

2023-03-24 17:58 UTC, JohanFreelancer9 requested changes
Copy review.

2023-03-25 02:05 UTC, scanum commented
@dariomws

2023-03-25 11:01 UTC, JohanFreelancer9 approved these changes

2023-03-30 05:39 UTC, scanum commented
@lilyolason 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-04-21 12:10 UTC, dariomws commented
@lilyolason
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-04-24 17:04 UTC, merged

2023-04-24 17:30 UTC, vstanche commented
Sorry don't understand why the request was closed, do not see anything changed in the public article?

Can you please advise?

2023-04-24 20:41 UTC, dariomws commented
@vstanche, you'll be able to see the updates in 24 hours.

2023-04-27 22:33 UTC, vstanche commented
Hello Dario,

Please be aware that updates are not there yet

***@***.***

Is that normal? Or the updates were done on another place?

Kind Regards,
***@***.***
***@***.***
Veselin Stanchev

Employee Experience / Viva SME, FastTrack for M365 EMEA

Customer Service & Support
***@***.******@***.***>





Microsoft Edge
The browser for business | Standardize on one browser with Microsoft security and innovation
Get assistance from FastTrack<https://www.microsoft.com/fasttrack> | Learn about Edge<https://www.microsoft.com/edge>
This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.

Microsoft Limited (company number 01624297) is a company registered in England and Wales whose registered office is at Microsoft Campus, Thames Valley Park, Reading RG6 1WG
If you have any feedback about my work, please let either myself or my manager know -  Mark Bebbington ***@***.******@***.***>

From: Dario Woitasen ***@***.***>
Sent: Monday, April 24, 2023 9:41 PM
To: MicrosoftDocs/Viva ***@***.***>
Cc: Veselin Stanchev ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/Viva] Update org-data-overview.md (PR #559)


@vstanche<https://github.com/vstanche>, you'll be able to see the updates in 24 hours.

-
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftDocs/Viva/pull/559#issuecomment-1520798190>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A4U5GA6PX2PQPVF4DPCJESLXC3QOVANCNFSM6AAAAAAWFA7PKQ>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2023-04-28 17:27 UTC, lilyolason commented
@dariomws and @vstanche , I'm checking in on this.

2023-04-30 23:19 UTC, vstanche commented
Thanks very much and really appreciate adding this content.

Just want to clarify something. According to the page

Azure Active Directory automatically syncs with the advanced insights app and provides data for these attributes:
*        PersonId
*        ManagerId
*        Organization
In your imported data, you'll also notice:
*        Domain, which Viva Insights gets from users' primary SMTP addresses.
*        TimeZone, which Viva Insights gets from users' Outlook/Exchange settings.

I think this is likely to create some confusion for our customers, why are the 1st three attributes categorized differently in comparison to domain and timezone. Domain and timezone are not automatically synced but they will be also noticed?

I am trying to determine if there is a difference in the mechanism between the 1st three and the other two?


Kind Regards,
***@***.***
***@***.***
Veselin Stanchev

Employee Experience / Viva SME, FastTrack for M365 EMEA

Customer Service & Support
***@***.******@***.***>





Microsoft Edge
The browser for business | Standardize on one browser with Microsoft security and innovation
Get assistance from FastTrack<https://www.microsoft.com/fasttrack> | Learn about Edge<https://www.microsoft.com/edge>
This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.

Microsoft Limited (company number 01624297) is a company registered in England and Wales whose registered office is at Microsoft Campus, Thames Valley Park, Reading RG6 1WG
If you have any feedback about my work, please let either myself or my manager know -  Mark Bebbington ***@***.******@***.***>

From: Lily Olason ***@***.***>
Sent: Friday, April 28, 2023 6:27 PM
To: MicrosoftDocs/Viva ***@***.***>
Cc: Veselin Stanchev ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/Viva] Update org-data-overview.md (PR #559)


@dariomws<https://github.com/dariomws> and @vstanche<https://github.com/vstanche> , I'm checking in on this.

-
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftDocs/Viva/pull/559#issuecomment-1527873394>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A4U5GA7H7ROKQMAY44U2KR3XDP4XXANCNFSM6AAAAAAWFA7PKQ>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>