Update overview-native-mode.md
MicrosoftDocs/Viva pull request #594
Opened 2023-05-04 13:56 UTC by anaritaroque

There are no Viva Engage/Native Mode Microsoft documentation that explains about bandwidth and Native Mode Migration. Already saw customers being block to perform the migration because there is no place in the documentation that ensures them that "There are no bandwidth requirements for the Native mode migration."

2023-05-05 04:10 UTC, JohanFreelancer9 commented on Viva/engage/overview-native-mode.md
> +> There are no bandwidth requirements for the Native mode migration. Essentially you are moving between Yammer separate site to Microsoft 365/SharePoint Online, nothing is downloaded. The only consid
```suggestion
> There are no bandwidth requirements for Native Mode migration because you are essentially moving from a separate Yammer site to Microsoft 365 and SharePoint Online, nothing is downloaded. The only consideration is the SharePoint Online quota should Yammer have been extensively used.
```

2023-05-05 04:12 UTC, JohanFreelancer9 requested changes
Copy review - @anaritaroque, kindly commit the suggested changes. Many thanks.

2023-05-05 10:19 UTC, JohanFreelancer9 commented on Viva/engage/overview-native-mode.md
> +
```suggestion
```

2023-05-05 10:20 UTC, JohanFreelancer9 requested changes
Apologies @anaritaroque, one more, please.

2023-05-05 13:48 UTC, JohanFreelancer9 approved these changes

2023-05-06 05:27 UTC, scanum commented
@dwhitfield233 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-05-10 04:29 UTC, scanum commented
@dwhitfield233
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-05-12 10:43 UTC, anaritaroque commented
Hello, if @dwhitfield233 is not available or able to approve it, is there anyone else that can do it @scanum ? Before the approval time expires.

Thank you for the attention here.

2023-05-15 04:43 UTC, scanum commented
@tiburd Hi Tina! Hope all is well. Could you please help with this PR? TY!

2023-05-22 23:07 UTC, merged