Update configure-sharepoint-content-source.md
MicrosoftDocs/Viva pull request #623
Opened 2023-06-09 23:06 UTC by Marweis

Updated a few pieces of information based on customer feedback. Feel free to revise wording and provide extra clarification as needed.

2023-06-10 06:10 UTC, JohanFreelancer9 commented on Viva/learning/configure-sharepoint-content-source.md
> +The site URL provided by the knowledge admin where the Learning App Content Repository resides needs to belong to the central location where your Microsoft 365 subscription was originally provisioned
```suggestion
The site URL provided by the knowledge admin where the Learning App Content Repository resides needs to belong to the central location where your Microsoft 365 subscription was originally provisioned (your default geo). 
```

2023-06-10 06:11 UTC, JohanFreelancer9 requested changes
Copy review - @Marweis, kindly commit the minor suggested change. Many thanks.

2023-06-12 14:33 UTC, JohanFreelancer9 approved these changes

2023-10-02 05:15 UTC, scanum commented
@bhaswatic 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2025-04-16 17:37 UTC, closed without merging