Documenting the Top News card behavior for boosted news
MicrosoftDocs/Viva pull request #645
Opened 2023-07-25 17:10 UTC by lucabandMSFT

2023-07-26 07:46 UTC, JohanFreelancer9 commented on Viva/connections/faqs-viva-connections-feed.md
> +
```suggestion
Posts will typically take up to 1 hour to appear in a user’s Feed.  Content from a newly created [home site](home-site-plan.md) is sometimes delayed for up to 24 hours after the site is initially created. After that initial 7-day period has passed, it will take up to 1 hour to appear.
```

2023-07-26 07:46 UTC, JohanFreelancer9 commented on Viva/connections/faqs-viva-connections-feed.md
> +In the [Feed for Viva Connections web part](/viva/connections/use-feed-web-part-for-viva-connections), news posts from [organizational news sites](/sharepoint/organization-news-site) up to 24 hours f
```suggestion
In the [Feed for Viva Connections web part](/viva/connections/use-feed-web-part-for-viva-connections), news posts from [organizational news sites](/sharepoint/organization-news-site) up to 24 hours from the post date will take precedence over older boosted news that has not yet reached the expiration. This can prevent boosted news from displaying prominently to end-users if the boosted news publishing date is older than the organizational news. Also, for [new organization news sites](/sharepoint/organization-news-site), it can take up to 24 hours for boosted news created from those sites to appear in the Top News card in Viva Connections dashboard.
```

2023-07-26 07:46 UTC, JohanFreelancer9 requested changes
Copy review - @lucabandMSFT, kindly commit the suggested changes. Many thanks.

2023-07-26 09:36 UTC, lucabandMSFT commented
> Copy review - @lucabandMSFT, kindly commit the suggested changes. Many thanks.

@JohanFreelancer9, thank you very much for your suggestions. Committed.

2023-07-26 13:59 UTC, JohanFreelancer9 approved these changes

2023-07-27 04:01 UTC, scanum commented
@Holland-ODSP 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-07-27 21:11 UTC, merged