Fix link and Clarify
MicrosoftDocs/Viva pull request #735
Opened 2023-10-10 00:53 UTC by get-itips

closes https://github.com/MicrosoftDocs/Viva/issues/721

2023-10-10 05:22 UTC, JohanFreelancer9 commented on Viva/learning/configure-sharepoint-content-source.md
> +If you encounter issues with content, refer to the [Manage Providers Configuration](/viva/learning/use-tabs.md#manage-providers-configuration) - export log, for detailed summaries of successful and f
```suggestion
If you encounter issues with content, refer to the [Manage Providers Configuration](/viva/learning/use-tabs.md#manage-providers-configuration) export log for detailed summaries of successful and failed content ingestions.
```

2023-10-10 05:22 UTC, JohanFreelancer9 requested changes
Copy review

2023-10-11 03:09 UTC, JohanFreelancer9 approved these changes

2023-10-13 01:16 UTC, scanum commented
@bhaswatic 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-16 05:25 UTC, merged