Add DraftMode parameter for setting Connections default experience
MicrosoftDocs/Viva pull request #739
Opened 2023-10-11 17:17 UTC by corriespondent

When running the Viva Connections default experience SPO Management Shell command as documented, the experience is in draft mode by default, thus removing the existing home site and global nav for users. I've added the DraftMode parameter and an explanation to clarify.

2023-10-12 05:38 UTC, JohanFreelancer9 commented on Viva/connections/edit-viva-home.md
> +   - Set the DraftMode parameter to **$false** to immediately enable the Connections desktop experience without going through the Admin Center.
```suggestion
   - The DraftMode parameter is set to **$true** by default, which will disable the global navigation and home site. The Connections desktop experience can be enabled in the Microsoft 365 admin center.
   - Set the DraftMode parameter to **$false** to immediately enable the Connections desktop experience without going through the admin center.
```

2023-10-12 05:41 UTC, JohanFreelancer9 requested changes
Copy review - @corriespondent, kindly commit the minor suggested change. Many thanks.

2023-10-12 15:29 UTC, JohanFreelancer9 approved these changes

2023-10-13 01:17 UTC, scanum commented
@AtkinE 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2025-04-16 18:55 UTC, lizap commented
@AtkinE - can you review whether this is a good change to make? Thanks!

2025-04-16 18:55 UTC, closed without merging